// Dummy-Daten für den Event-Kalender
// Events von 8:00 bis 14:00 Uhr, 30-Minuten-Slots

export const calendarEvents = [
  // Montag, 10. November 2025
  {
    id: 'mon-1',
    day: 'montag',
    startTime: '08:00',
    duration: 30,
    speakerName: 'Dr. Anna Müller',
    speakerImage: null,
    description: 'Eröffnungs-Keynote: Willkommen zu den Inspiration Days. Ein Blick auf die Zukunft der Technologie.',
  },
  {
    id: 'mon-2',
    day: 'montag',
    startTime: '08:30',
    duration: 30,
    speakerName: 'Thomas Schmidt',
    speakerImage: null,
    description: 'Innovation in der Praxis: Wie Startups die Tech-Branche revolutionieren.',
  },
  {
    id: 'mon-3',
    day: 'montag',
    startTime: '09:00',
    duration: 30,
    speakerName: 'Lisa Weber',
    speakerImage: null,
    description: 'Design Thinking: Kreative Problemlösung für komplexe Herausforderungen.',
  },
  {
    id: 'mon-4',
    day: 'montag',
    startTime: '09:00',
    duration: 30,
    speakerName: 'Mark Hoffmann',
    speakerImage: null,
    description: 'Agile Methoden: Scrum und Kanban im modernen Projektmanagement.',
  },
  {
    id: 'mon-5',
    day: 'montag',
    startTime: '09:30',
    duration: 30,
    speakerName: 'Sophie Becker',
    speakerImage: null,
    description: 'User Experience: Die Kunst des nutzerzentrierten Designs.',
  },
  {
    id: 'mon-6',
    day: 'montag',
    startTime: '10:00',
    duration: 30,
    speakerName: 'Peter Fischer',
    speakerImage: null,
    description: 'Data Analytics: Mit Daten bessere Entscheidungen treffen.',
  },
  {
    id: 'mon-7',
    day: 'montag',
    startTime: '10:30',
    duration: 30,
    speakerName: 'Julia Klein',
    speakerImage: null,
    description: 'Digital Marketing: Strategien für die digitale Transformation.',
  },
  {
    id: 'mon-8',
    day: 'montag',
    startTime: '11:00',
    duration: 30,
    speakerName: 'Robert Lang',
    speakerImage: null,
    description: 'E-Commerce: Erfolgreiche Online-Shops aufbauen und optimieren.',
  },
  {
    id: 'mon-9',
    day: 'montag',
    startTime: '11:00',
    duration: 30,
    speakerName: 'Nina Bauer',
    speakerImage: null,
    description: 'Content Strategy: Storytelling für digitale Medien.',
  },
  {
    id: 'mon-10',
    day: 'montag',
    startTime: '11:30',
    duration: 30,
    speakerName: 'Christian Wolf',
    speakerImage: null,
    description: 'Projektmanagement: Von der Idee zur erfolgreichen Umsetzung.',
  },
  {
    id: 'mon-11',
    day: 'montag',
    startTime: '12:00',
    duration: 30,
    speakerName: 'Maria Schneider',
    speakerImage: null,
    description: 'Team Leadership: Erfolgreiche Teams führen und motivieren.',
  },
  {
    id: 'mon-12',
    day: 'montag',
    startTime: '12:30',
    duration: 30,
    speakerName: 'Andreas Meyer',
    speakerImage: null,
    description: 'Networking Session: Kontakte knüpfen und Erfahrungen austauschen.',
  },

  // Dienstag, 11. November 2025
  {
    id: 'tue-3',
    day: 'dienstag',
    startTime: '09:00',
    duration: 30,
    speakerName: 'Christian Redl',
    speakerImage: '/logos/Speaker/christian_redl.jpg',
    description: 'Weltrekordhalter und Extremsportler, der zeigt, wie mentale Stärke und Zielstrebigkeit Grenzen verschieben können.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-4',
    day: 'dienstag',
    startTime: '09:00',
    duration: 30,
    speakerName: 'Tim Bengel',
    speakerImage: '/logos/Speaker/tim_bengel.png',
    description: 'Künstler und Unternehmer, der mit innovativen Materialien und Ideen die Kunstwelt erobert.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-5',
    day: 'dienstag',
    startTime: '09:30',
    duration: 30,
    speakerName: 'Suzanna Randall',
    speakerImage: '/logos/Speaker/suzanna_randall.jpg',
    description: 'Astrophysikerin und angehende Astronautin, die Einblicke in Raumfahrt und Wissenschaftskarrieren gibt.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-6',
    day: 'dienstag',
    startTime: '10:00',
    duration: 30,
    speakerName: 'Anne Blatter-Miredin',
    speakerImage: '/logos/Speaker/Anne_Blatter-Miredin.png',
    description: 'Kreative Konditormeisterin, die zeigt, wie man Leidenschaft und Handwerk in süße Kunst verwandelt.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-7',
    day: 'dienstag',
    startTime: '10:30',
    duration: 30,
    speakerName: 'Mariem Kthiri',
    speakerImage: '/logos/Speaker/mariem_kthiri.png',
    description: 'Expertin für Künstliche Intelligenz bei Amazon, die über Karrierewege und Zukunftschancen im Tech-Bereich spricht.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-8',
    day: 'dienstag',
    startTime: '11:00',
    duration: 30,
    speakerName: 'Karolina Decker',
    speakerImage: '/logos/Speaker/karolina_decker.png',
    description: 'Gründerin von Schulgold, einer Plattform für Finanzbildung, die junge Menschen fit im Umgang mit Geld macht.',
    eventType: 'Workshop',
  },
  {
    id: 'tue-9',
    day: 'dienstag',
    startTime: '11:00',
    duration: 30,
    speakerName: 'Paula Schwarz',
    speakerImage: '/logos/Speaker/paula_schwarz.png',
    description: 'Unternehmerin und Philanthropin, die über soziale Verantwortung und nachhaltiges Unternehmertum spricht.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-10',
    day: 'dienstag',
    startTime: '11:30',
    duration: 30,
    speakerName: 'Ausbildung bei Amazon',
    speakerImage: '/logos/Speaker/amazon_logo.jpg',
    description: 'Mit Robotern arbeiten: Einblick in die vielseitige Ausbildung zum Mechatroniker bei Amazon.',
    eventType: 'Panel',
  },
  {
    id: 'tue-11',
    day: 'dienstag',
    startTime: '12:00',
    duration: 30,
    speakerName: 'House of Communications',
    speakerImage: '/logos/Speaker/house_of_communication.jpeg',
    description: 'Kreativagentur, die zeigt, wie Kommunikation, Marketing und Medien im modernen Berufsleben zusammenspielen.',
    eventType: 'Panel',
  },
  {
    id: 'tue-12',
    day: 'dienstag',
    startTime: '12:30',
    duration: 30,
    speakerName: 'Bastian Hopfgarten',
    speakerImage: '/logos/Speaker/bastian_hopfgarten.jpg',
    description: 'Spezialist für visuelle Effekte in Film und Fernsehen, der hinter die Kulissen spektakulärer Produktionen blickt.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-13',
    day: 'dienstag',
    startTime: '12:30',
    duration: 30,
    speakerName: 'Ausbildung bei RWE',
    speakerImage: '/logos/Speaker/RWE_logo.png',
    description: 'Erfahre, welche spannenden technischen und nachhaltigen Ausbildungsberufe RWE im Offshore-Bereich bietet.',
    eventType: 'Panel',
  },
  {
    id: 'tue-14',
    day: 'dienstag',
    startTime: '13:00',
    duration: 30,
    speakerName: 'Mohammad Al-Kurdi',
    speakerImage: '/logos/Speaker/mohammad_al_kurdi.png',
    description: 'Gründer und Unternehmer, der Bildung und Kreativität erfolgreich verbindet.',
    eventType: 'Live-Talk',
  },
  {
    id: 'tue-16',
    day: 'dienstag',
    startTime: '13:30',
    duration: 30,
    speakerName: 'Dominique Herold',
    speakerImage: '/logos/Speaker/Dominique_Herold.jpg',
    description: 'Floristikmeisterin, die erzählt, wie man mit Kreativität und Naturgefühl einen blühenden Beruf gestalten kann.',
    eventType: 'Live-Talk',
  },
  // Mittwoch, 12. November 2025
  {
    id: 'wed-1',
    day: 'mittwoch',
    startTime: '08:45',
    duration: 45,
    speakerName: 'Kerstin Kriha',
    speakerImage: '/logos/Speaker/kerstin_kriha.jpeg',
    description: 'KI Expertin bei Amazon, die in einem spannenden Quiz durch die Welt eines Rechenzentrums von Amazon Web Services führt.',
    eventType: 'Live Quiz',
  },
  {
    id: 'wed-2',
    day: 'mittwoch',
    startTime: '09:30',
    duration: 30,
    speakerName: 'René Rennefeld',
    speakerImage: '/logos/Speaker/rene_rennefeld.jpg',
    description: 'Musikproduzent und Keynote-Speaker, der zeigt, wie man Leidenschaft in Beruf und Erfolg verwandelt.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-3',
    day: 'mittwoch',
    startTime: '10:00',
    duration: 30,
    speakerName: 'Dr. Monika V. Kronbügel',
    speakerImage: '/logos/Speaker/monika-kronbügel.jpg',
    description: 'Unternehmerin und Mentorin, die über Karriere, Leadership und persönliche Entwicklung spricht.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-4',
    day: 'mittwoch',
    startTime: '10:00',
    duration: 30,
    speakerName: 'Philipp Frisch',
    speakerImage: '/logos/Speaker/philipp_frisch.webp',
    description: 'Geschäftsführer von Human Rights Watch Deutschland, der über Menschenrechte und zivilgesellschaftliches Engagement spricht.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-5',
    day: 'mittwoch',
    startTime: '10:30',
    duration: 30,
    speakerName: 'Peek & Cloppenburg',
    speakerImage: '/logos/Speaker/p&c.png',
    description: 'Lerne die vielfältigen Ausbildungswege in Mode, Verkauf und Management bei P&C kennen.',
    eventType: 'Panel',
  },
  {
    id: 'wed-6',
    day: 'mittwoch',
    startTime: '11:00',
    duration: 30,
    speakerName: 'Lehrerworkshop mit Schulgold',
    speakerImage: '/logos/Speaker/schulgold_logo.png',
    description: 'Gründerin von Schulgold, einer Plattform für Finanzbildung, die junge Menschen fit im Umgang mit Geld macht.',
    eventType: 'Workshop',
  },
  {
    id: 'wed-6b',
    day: 'mittwoch',
    startTime: '11:00',
    duration: 30,
    speakerName: 'Dr. Ralf Höcker',
    speakerImage: '/logos/Speaker/ralf_höcker.jpg',
    description: 'Medienanwalt und Kommunikationsexperte, der über Recht, Meinungsfreiheit und den Umgang mit öffentlicher Darstellung in der digitalen Welt spricht.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-7',
    day: 'mittwoch',
    startTime: '11:30',
    duration: 30,
    speakerName: 'Fabian Ritter',
    speakerImage: '/logos/Speaker/fabian_ritter.png',
    description: 'Meeresforscher, der vom Schutz der Ozeane und spannenden Forschungsreisen erzählt.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-7b',
    day: 'mittwoch',
    startTime: '11:30',
    duration: 30,
    speakerName: 'Schülerworkshop mit Schulgold',
    speakerImage: '/logos/Speaker/schulgold_logo.png',
    description: 'Gründerin von Schulgold, einer Plattform für Finanzbildung, die junge Menschen fit im Umgang mit Geld macht.',
    eventType: 'Workshop',
  },
  {
    id: 'wed-8',
    day: 'mittwoch',
    startTime: '12:00',
    duration: 30,
    speakerName: 'Roland Buß',
    speakerImage: '/logos/Speaker/roland_buß.jpeg',
    description: 'Experte für Jugend- und Bildungsthemen, der Orientierung im Berufsdschungel gibt.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-9',
    day: 'mittwoch',
    startTime: '12:30',
    duration: 30,
    speakerName: 'Ausbildung bei Amazon',
    speakerImage: '/logos/Speaker/amazon_logo.jpg',
    description: 'Mit Robotern arbeiten: Einblick in die vielseitige Ausbildung zum Mechatroniker bei Amazon.',
    eventType: 'Panel',
  },
  {
    id: 'wed-10',
    day: 'mittwoch',
    startTime: '12:30',
    duration: 30,
    speakerName: 'Benedict Wells',
    speakerImage: '/logos/Speaker/benedict_wells.jpg',
    description: 'Bestsellerautor, der über Kreativität, Schreiben und seinen Weg in die Literatur spricht.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-11',
    day: 'mittwoch',
    startTime: '13:00',
    duration: 30,
    speakerName: 'Ausbildung bei der Deutschen Flugsicherung',
    speakerImage: '/logos/Speaker/DFS.jpg',
    description: 'Erfahre, wie du mit Technik, Präzision und Verantwortung in die Welt der Luftfahrt einsteigen kannst.',
    eventType: 'Panel',
  },
  {
    id: 'wed-12',
    day: 'mittwoch',
    startTime: '13:00',
    duration: 30,
    speakerName: 'Josha Salchow',
    speakerImage: '/logos/Speaker/Josha_Salchow.webp',
    description: 'Leistungssportler, der über Disziplin, Motivation und den Weg zum Erfolg spricht.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-13',
    day: 'mittwoch',
    startTime: '13:30',
    duration: 30,
    speakerName: 'Thomas Diehl',
    speakerImage: '/logos/Speaker/thomas_diehl.jpg',
    description: 'Winzer, der Einblicke in nachhaltigen Weinbau und Handwerk als Lebensweg gibt.',
    eventType: 'Live-Talk',
  },
  {
    id: 'wed-13b',
    day: 'mittwoch',
    startTime: '13:30',
    duration: 45,
    speakerName: 'Julian Behnke',
    speakerImage: '/logos/Speaker/julian_behnke.png',
    description: 'IT Project Engineer bei Amazon und Ausbilder für Fachinformatik, der in einem spannenden Quiz durch die Welt eines Logistikzentrums führt.',
    eventType: 'Live-Quiz',
  },
  {
    id: 'wed-14',
    day: 'mittwoch',
    startTime: '14:00',
    duration: 30,
    speakerName: 'Sofia Saraiva de Figueiredo',
    speakerImage: '/logos/Speaker/sofia_saraiva.png',
    description: 'Sofia wanderte aus Brasilien nach Deutschland aus, um ihre Ausbildung als Fachinformatikerin für Systemintegration bei AWS zu absolvieren. Hier arbeitet sie jeden Tag mit modernster Technologie.',
    eventType: 'Live-Talk',
  },

  // Donnerstag, 13. November 2025
  {
    id: 'thu-1',
    day: 'donnerstag',
    startTime: '08:30',
    duration: 30,
    speakerName: 'Gianni Matheja – präsentiert FU Berlin',
    speakerImage: '/logos/Speaker/Gianni.jpeg',
    description: 'Gianni ist nicht nur erfolgreicher Creator sondern auch Student und gibt dir Einblicke in seinen Werdegang.',
    eventType: 'Live-Talk',
  },
  {
    id: 'thu-2',
    day: 'donnerstag',
    startTime: '09:15',
    duration: 30,
    speakerName: 'Generative AI Foundations',
    speakerImage: '/logos/Speaker/amazon_logo.jpg',
    description: 'Einführung in generative Künstliche Intelligenz und ihre Anwendung im Berufsleben.',
    eventType: 'Live-Talk',
  },
  {
    id: 'thu-3',
    day: 'donnerstag',
    startTime: '10:30',
    duration: 30,
    speakerName: 'Gründerpanel mit Stefan Krause',
    speakerImage: '/logos/Speaker/stefan_krause.png',
    description: 'Diskussion mit Gründerpersönlichkeiten über Innovation, Risiko und Unternehmertum.',
    eventType: 'Panel',
  },
  {
    id: 'thu-3b',
    day: 'donnerstag',
    startTime: '10:00',
    duration: 30,
    speakerName: 'Quiz Tour für Schüler',
    speakerImage: '/logos/Speaker/amazon_logo.jpg',
    description: 'Interaktives Quiz rund um Berufsorientierung, Technik und Zukunft bei Amazon.',
    eventType: 'Live Quiz',
  },
  {
    id: 'thu-4',
    day: 'donnerstag',
    startTime: '11:00',
    duration: 30,
    speakerName: 'Hochstapeln erlaubt: mit dualer Ausbildung!',
    speakerImage: '/logos/Speaker/IHK.png',
    description: 'Talk der IHK Berlin über Karrierechancen durch duale Ausbildung.',
    eventType: 'Panel',
  },
  {
    id: 'thu-4c',
    day: 'donnerstag',
    startTime: '11:40',
    duration: 50,
    speakerName: 'PartyRock für Lehrkräfte',
    speakerImage: '/logos/Speaker/amazon_logo.jpg',
    description: 'Entdecken Sie, wie Sie mit PartyRock ohne Programmierkenntnisse KI-Anwendungen erstellen können, die Ihnen sowohl bei der Unterrichtsvorbereitung helfen als auch das Verständnis dafür vermitteln, wie KI tatsächlich funktioniert.',
    eventType: 'Workshop',
  },
  {
    id: 'thu-5',
    day: 'donnerstag',
    startTime: '11:45',
    duration: 30,
    speakerName: 'Kreativpanel',
    speakerImage: '/logos/Speaker/Stoopid_Lou.png',
    speakerImage2: '/logos/Speaker/alexander_martini.png',
    description: 'Musikproduzent Stoopid Lou und Künstler Alexander Martini sprechen über ihre Wege in die Kulturbranche.',
    eventType: 'Panel',
  },
  {
    id: 'thu-6',
    day: 'donnerstag',
    startTime: '12:30',
    duration: 30,
    speakerName: 'Theresia Crone',
    speakerImage: '/logos/Speaker/Theresia_Crone.jpg',
    description: 'Jung-Aktivistin Theresia Crone spricht über gesellschaftlichen Wandel und Jugendbeteiligung.',
    eventType: 'Live-Talk',
  },
  {
    id: 'thu-6c',
    day: 'donnerstag',
    startTime: '12:30',
    duration: 45,
    speakerName: 'Lehrerworkshop mit Schulgold',
    speakerImage: '/logos/Speaker/schulgold_logo.png',
    description: 'Gründerin von Schulgold, einer Plattform für Finanzbildung, die junge Menschen fit im Umgang mit Geld macht.',
    eventType: 'Workshop',
  },
  {
    id: 'thu-7',
    day: 'donnerstag',
    startTime: '13:30',
    duration: 15,
    speakerName: 'Bettina Stix',
    speakerImage: '/logos/Speaker/bettina_strix.jpg',
    description: 'Verantwortet bei Amazon weltweit das gesellschaftliche Engagement.',
    eventType: 'Live-Talk',
  },
  {
    id: 'thu-8',
    day: 'donnerstag',
    startTime: '13:45',
    duration: 30,
    speakerName: 'Susanne Bretfeld',
    speakerImage: '/logos/Speaker/susanne_bretfeld.webp',
    description: 'Zwischen TikTok und Superintelligenz: Der Tech-Shift von Gen Y zu „Gen AI"',
    eventType: 'Live-Talk',
  },
  {
    id: 'thu-10',
    day: 'donnerstag',
    startTime: '14:15',
    duration: 30,
    speakerName: 'Film-Panel',
    speakerImage: '/logos/Speaker/Sebastian_Filmstarts.jpeg',
    speakerImage2: '/logos/Speaker/Alexander_Wadouh.jpg',
    description: 'Ein Panel über die Liebe zum Film mit Sebastian Gerdshikow von Filmstarts und Produzent Alexander Wadouh.',
    eventType: 'Panel',
  },
  {
    id: 'thu-11',
    day: 'donnerstag',
    startTime: '17:00',
    duration: 60,
    speakerName: 'Community Panel',
    speakerImage: '/logos/Speaker/Julian_Rauch.webp',
    speakerImage2: '/logos/Speaker/Irene_Kilubi.avif',
    speakerImage3: '/logos/Speaker/Sabrina_Konzok .jpg',
    speakerImage4: '/logos/Speaker/lisa_marie_Meloen.jpeg',
    description: 'Wie gelingt Community-Wachstum – von den ersten 100 Mitgliedern bis zur nachhaltigen Skalierung. Mit Julian Rauch, Iréne Kilubi, Sabrina Konzok und moderiert von Lisa Marie Meloen.',
    eventType: 'Panel',
    fullWidth: true,
  },
  {
    id: 'thu-12',
    day: 'donnerstag',
    startTime: '18:15',
    duration: 60,
    speakerName: 'KI Panel',
    speakerImage: '/logos/Speaker/Udo_Schloemer_2.jpg',
    speakerImage2: '/logos/Speaker/Georg_Müller_Loeffelholz.jpg',
    speakerImage3: '/logos/Speaker/Dorothea_Winter_2.jpg',
    speakerImage4: '/logos/Speaker/martin_murphy.png',
    description: 'Wie wir in einer Zukunft mit KI leben, lernen und arbeiten werden. Mit Udo Schloemer, Georg Müller-Loeffelholz, Dorothea Winter und moderiert von Martin Murphy.',
    eventType: 'Panel',
    fullWidth: true,
  },
]

